"""add_resume_id_to_interviews

Revision ID: 5f11859b5348
Revises: 75b0cfeaa4eb
Create Date: 2026-06-05 22:51:14.327924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f11859b5348'
down_revision = '75b0cfeaa4eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('resume_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'resume_id')
    # ### end Alembic commands ###
